/********************************************
 *            AUTOGENERATED FILE            *
 *             DO NOT MODIFY IT             *
 *                                          *
 * To add new commands :                    *
 *  - Modify ../Xml/commands.xml file       *
 *  - Re-run generateCommandsList.py script *
 *                                          *
 ********************************************/
#include <libARCommands/commandsList.h>
#include <stdlib.h>

libARCommandsCmd_t ***libARCommandsCmdList = NULL;
int *libARCommandsCmdTypesMaxId = NULL;
int libARCommandsCmdListInitOk = 0;


libARCommandsCmd_t **pilotingCommandsList = NULL;

libARCommandsCmd_t piloting_takeoff_cmd = { LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t piloting_pcmd_cmd = { LIBARCOMMANDS_ARG_TYPE_FLOAT, LIBARCOMMANDS_ARG_TYPE_FLOAT, LIBARCOMMANDS_ARG_TYPE_FLOAT, LIBARCOMMANDS_ARG_TYPE_FLOAT, LIBARCOMMANDS_ARG_TYPE_FLOAT, LIBARCOMMANDS_ARG_TYPE_FLOAT, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t piloting_landing_cmd = { LIBARCOMMANDS_ARG_TYPE_END };

libARCommandsCmd_t **configCommandsList = NULL;

libARCommandsCmd_t config_ssid_cmd = { LIBARCOMMANDS_ARG_TYPE_STRING, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t config_angle_max_cmd = { LIBARCOMMANDS_ARG_TYPE_FLOAT, LIBARCOMMANDS_ARG_TYPE_END };

libARCommandsCmd_t **testCommandsList = NULL;

libARCommandsCmd_t test_u8_cmd = { LIBARCOMMANDS_ARG_TYPE_U8, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_i8_cmd = { LIBARCOMMANDS_ARG_TYPE_I8, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_u16_cmd = { LIBARCOMMANDS_ARG_TYPE_U16, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_i16_cmd = { LIBARCOMMANDS_ARG_TYPE_I16, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_u32_cmd = { LIBARCOMMANDS_ARG_TYPE_U32, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_i32_cmd = { LIBARCOMMANDS_ARG_TYPE_I32, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_u64_cmd = { LIBARCOMMANDS_ARG_TYPE_U64, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_i64_cmd = { LIBARCOMMANDS_ARG_TYPE_I64, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_float_cmd = { LIBARCOMMANDS_ARG_TYPE_FLOAT, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_double_cmd = { LIBARCOMMANDS_ARG_TYPE_DOUBLE, LIBARCOMMANDS_ARG_TYPE_END };
libARCommandsCmd_t test_string_cmd = { LIBARCOMMANDS_ARG_TYPE_STRING, LIBARCOMMANDS_ARG_TYPE_END };



int libARCommandsListInit ()
{
    int res = 1;
    if (1 == libARCommandsListInitOk)
    {
        return libARCommandsListInitOk;
    }

    if (1 == res)
    {
        pilotingCommandsList = calloc (PILOTING_CMD_MAX, sizeof (libARCommandsCmd_t));
        if (NULL != pilotingCommandsList)
        {
            pilotingCommandsList [PILOTING_CMD_TAKEOFF] = &piloting_takeoff_cmd;
            pilotingCommandsList [PILOTING_CMD_PCMD] = &piloting_pcmd_cmd;
            pilotingCommandsList [PILOTING_CMD_LANDING] = &piloting_landing_cmd;
        }
        else
        {
            res = 0;
        }
    }

    if (1 == res)
    {
        configCommandsList = calloc (CONFIG_CMD_MAX, sizeof (libARCommandsCmd_t));
        if (NULL != configCommandsList)
        {
            configCommandsList [CONFIG_CMD_SSID] = &config_ssid_cmd;
            configCommandsList [CONFIG_CMD_ANGLE_MAX] = &config_angle_max_cmd;
        }
        else
        {
            res = 0;
        }
    }

    if (1 == res)
    {
        testCommandsList = calloc (TEST_CMD_MAX, sizeof (libARCommandsCmd_t));
        if (NULL != testCommandsList)
        {
            testCommandsList [TEST_CMD_U8] = &test_u8_cmd;
            testCommandsList [TEST_CMD_I8] = &test_i8_cmd;
            testCommandsList [TEST_CMD_U16] = &test_u16_cmd;
            testCommandsList [TEST_CMD_I16] = &test_i16_cmd;
            testCommandsList [TEST_CMD_U32] = &test_u32_cmd;
            testCommandsList [TEST_CMD_I32] = &test_i32_cmd;
            testCommandsList [TEST_CMD_U64] = &test_u64_cmd;
            testCommandsList [TEST_CMD_I64] = &test_i64_cmd;
            testCommandsList [TEST_CMD_FLOAT] = &test_float_cmd;
            testCommandsList [TEST_CMD_DOUBLE] = &test_double_cmd;
            testCommandsList [TEST_CMD_STRING] = &test_string_cmd;
        }
        else
        {
            res = 0;
        }
    }


    if (1 == res)
    {
        libARCommandsCmdList = calloc (COMMAND_TYPE_MAX, sizeof (libARCommandsCmd_t *));
        if (NULL != libARCommandsCmdList)
        {
            libARCommandsCmdList [COMMAND_TYPE_PILOTING] = pilotingCommandsList;
            libARCommandsCmdList [COMMAND_TYPE_CONFIG] = configCommandsList;
            libARCommandsCmdList [COMMAND_TYPE_TEST] = testCommandsList;
        }
        else
        {
            res = 0;
        }
    }

    if (1 == res)
    {
        libARCommandsCmdTypesMaxId = calloc (COMMAND_TYPE_MAX, sizeof (int));
        if (NULL != libARCommandsCmdTypesMaxId)
        {
            libARCommandsCmdTypesMaxId [COMMAND_TYPE_PILOTING] = PILOTING_CMD_MAX;
            libARCommandsCmdTypesMaxId [COMMAND_TYPE_CONFIG] = CONFIG_CMD_MAX;
            libARCommandsCmdTypesMaxId [COMMAND_TYPE_TEST] = TEST_CMD_MAX;
        }
        else
        {
            res = 0;
        }
    }

    if (0 == res)
    {
        libARCommandsListDestroy ();
    }
    else
    {
        libARCommandsListInitOk = res;
    }
    return res;
}


void libARCommandsListDestroy ()
{
    if (NULL != pilotingCommandsList) { free (pilotingCommandsList); pilotingCommandsList = NULL; }
    if (NULL != configCommandsList) { free (configCommandsList); configCommandsList = NULL; }
    if (NULL != testCommandsList) { free (testCommandsList); testCommandsList = NULL; }
    if (NULL != libARCommandsCmdList) { free (libARCommandsCmdList); libARCommandsCmdList = NULL; }
    if (NULL != libARCommandsCmdTypesMaxId) { free (libARCommandsCmdTypesMaxId); libARCommandsCmdTypesMaxId = NULL; }
    libARCommandsListInitOk = 0;
}
