from xml.dom.minidom import parseString
import sys

file = open ('./commands.xml', 'r')
data = file.read ()
file.close ()

cfile = open ('../Sources/commandsList.c', 'w')
hfile = open ('../Includes/libARCommands/commandsList.h', 'w')

xmlfile = parseString (data)

alltypes = []
alltypesNames = []

types = xmlfile.getElementsByTagName('type')
cfile.write ('/********************************************\n')
cfile.write (' *            AUTOGENERATED FILE            *\n')
cfile.write (' *             DO NOT MODIFY IT             *\n')
cfile.write (' *                                          *\n')
cfile.write (' * To add new commands :                    *\n')
cfile.write (' *  - Modify ../Xml/commands.xml file       *\n')
cfile.write (' *  - Re-run generateCommandsList.py script *\n')
cfile.write (' *                                          *\n')
cfile.write (' ********************************************/\n')
cfile.write ('#include <libARCommands/commandsList.h>\n')
cfile.write ('#include <stdlib.h>\n')
cfile.write ('\n')
cfile.write ('libARCommandsCmd_t ***libARCommandsCmdList = NULL;\n')
cfile.write ('int *libARCommandsCmdTypesMaxId = NULL;\n')
cfile.write ('int libARCommandsCmdListInitOk = 0;\n')
cfile.write ('\n')
cfile.write ('\n')
for cmdtype in types:
    typename = cmdtype.getElementsByTagName('tname')[0].firstChild.data
    cfile.write ('libARCommandsCmd_t **' + typename + 'CommandsList = NULL;\n')
    cfile.write ('\n')
    alltypesNames.append (typename)
    currtype = []
    commands = cmdtype.getElementsByTagName('cmd')
    for command in commands:
        commandname = command.getElementsByTagName('cname')[0].firstChild.data
        commandname = commandname.replace (' ', '_')
        cfile.write ('libARCommandsCmd_t ' + typename + '_' + commandname + '_cmd = { ')
        currtype.append (commandname)
        args = command.getElementsByTagName('arg')
        for arg in args:
            argtype = arg.firstChild.data.upper()
            cfile.write ('LIBARCOMMANDS_ARG_TYPE_' + argtype + ', ')
        cfile.write ('LIBARCOMMANDS_ARG_TYPE_END };\n')
    alltypes.append(currtype)
    cfile.write ('\n')

cfile.write ('\n')
cfile.write ('\n')
cfile.write ('int libARCommandsListInit ()\n')
cfile.write ('{\n')
cfile.write ('    int res = 1;\n')
cfile.write ('    if (1 == libARCommandsListInitOk)\n')
cfile.write ('    {\n')
cfile.write ('        return libARCommandsListInitOk;\n')
cfile.write ('    }\n')
cfile.write ('\n')
for type in alltypesNames:
    cfile.write ('    if (1 == res)\n')
    cfile.write ('    {\n')
    sname = type + 'CommandsList'
    cfile.write ('        ' + sname + ' = calloc (' + type.upper () + '_CMD_MAX, sizeof (libARCommandsCmd_t));\n')
    cfile.write ('        if (NULL != ' + sname + ')\n')
    cfile.write ('        {\n')
    cmdlist = alltypes [alltypesNames.index (type)]
    for cmd in cmdlist:
        cfile.write ('            ' + sname + ' [' + type.upper () + '_CMD_' + cmd.upper () + '] = &' + type + '_' + cmd + '_cmd;\n')
    cfile.write ('        }\n')
    cfile.write ('        else\n')
    cfile.write ('        {\n')
    cfile.write ('            res = 0;\n')
    cfile.write ('        }\n')
    cfile.write ('    }\n')
    cfile.write ('\n')
cfile.write ('\n')

cfile.write ('    if (1 == res)\n')
cfile.write ('    {\n')
cfile.write ('        libARCommandsCmdList = calloc (COMMAND_TYPE_MAX, sizeof (libARCommandsCmd_t *));\n')
cfile.write ('        if (NULL != libARCommandsCmdList)\n')
cfile.write ('        {\n')
for type in alltypesNames:
    cfile.write ('            libARCommandsCmdList [COMMAND_TYPE_' + type.upper () + '] = ' + type + 'CommandsList;\n')
cfile.write ('        }\n')
cfile.write ('        else\n')
cfile.write ('        {\n')
cfile.write ('            res = 0;\n')
cfile.write ('        }\n')
cfile.write ('    }\n')
cfile.write ('\n')

cfile.write ('    if (1 == res)\n')
cfile.write ('    {\n')
cfile.write ('        libARCommandsCmdTypesMaxId = calloc (COMMAND_TYPE_MAX, sizeof (int));\n')
cfile.write ('        if (NULL != libARCommandsCmdTypesMaxId)\n')
cfile.write ('        {\n')
for type in alltypesNames:
    cfile.write ('            libARCommandsCmdTypesMaxId [COMMAND_TYPE_' + type.upper () + '] = ' + type.upper () + '_CMD_MAX;\n')
cfile.write ('        }\n')
cfile.write ('        else\n')
cfile.write ('        {\n')
cfile.write ('            res = 0;\n')
cfile.write ('        }\n')
cfile.write ('    }\n')
cfile.write ('\n')

cfile.write ('    if (0 == res)\n')
cfile.write ('    {\n')
cfile.write ('        libARCommandsListDestroy ();\n')
cfile.write ('    }\n')
cfile.write ('    else\n')
cfile.write ('    {\n')
cfile.write ('        libARCommandsListInitOk = res;\n')
cfile.write ('    }\n')
cfile.write ('    return res;\n')
cfile.write ('}\n')
cfile.write ('\n')
cfile.write ('\n')

cfile.write ('void libARCommandsListDestroy ()\n')
cfile.write ('{\n')
for type in alltypesNames:
    sname = type + 'CommandsList'
    cfile.write ('    if (NULL != ' + sname + ') { free (' + sname + '); ' + sname + ' = NULL; }\n')
cfile.write ('    if (NULL != libARCommandsCmdList) { free (libARCommandsCmdList); libARCommandsCmdList = NULL; }\n')
cfile.write ('    if (NULL != libARCommandsCmdTypesMaxId) { free (libARCommandsCmdTypesMaxId); libARCommandsCmdTypesMaxId = NULL; }\n')
cfile.write ('    libARCommandsListInitOk = 0;\n')
cfile.write ('}\n')
cfile.write ('\n')


cfile.write ('libARCommandsCmd_t *getCommandArgsWithTypeAndId (eLIBARCOMMANDS_ARG_TYPE type, int id)\n')
cfile.write ('{\n')
cfile.write ('    libARCommandsCmd_t *retVal = NULL;\n')
cfile.write ('    int maxId = 0;\n')
cfile.write ('\n')
cfile.write ('    if (0 == libARCommandsListInitOk && 1 != libARCommandsListInit ())\n')
cfile.write ('    {\n')
cfile.write ('        SAL_PRINT (PRINT_ERROR, "Unable to initialize libARCommandsList\\n");\n')
cfile.write ('        return NULL;\n')
cfile.write ('    }\n')
cfile.write ('    if (COMMAND_TYPE_MAX <= type)\n')
cfile.write ('    {\n')
cfile.write ('        SAL_PRINT (PRINT_DEBUG, "Type %d is unknown (I know only %d types)\\n", type, COMMAND_TYPE_MAX);\n')
cfile.write ('        return NULL;\n')
cfile.write ('    }\n')
cfile.write ('    maxId = libARCommandsCmdTypesMaxId [type];\n')
cfile.write ('    if (maxId <= id)\n')
cfile.write ('    {\n')
cfile.write ('        SAL_PRINT (PRINT_DEBUG, "Id %d is unknown for type %d (I know only %d id to this type)\\n", id, type, maxId);\n')
cfile.write ('        return NULL;\n')
cfile.write ('    }\n')
cfile.write ('    return libARCommandsCmdList [type][id];\n')
cfile.write ('}\n')

cfile.close ()



hfile.write ('/********************************************\n')
hfile.write (' *            AUTOGENERATED FILE            *\n')
hfile.write (' *             DO NOT MODIFY IT             *\n')
hfile.write (' *                                          *\n')
hfile.write (' * To add new commands :                    *\n')
hfile.write (' *  - Modify ../../Xml/commands.xml file    *\n')
hfile.write (' *  - Re-run generateCommandsList.py script *\n')
hfile.write (' *                                          *\n')
hfile.write (' ********************************************/\n')
hfile.write ('\n')
hfile.write ('#ifndef _LIBARCOMMANDS_COMMANDS_LIST_H_\n')
hfile.write ('#define _LIBARCOMMANDS_COMMANDS_LIST_H_ (1)\n')
hfile.write ('\n')
hfile.write ('#include <libARCommands/commandsTypes.h>\n')
hfile.write ('\n')
hfile.write ('typedef enum {\n')
first = 1
for type in alltypesNames:
    if 1 == first:
        hfile.write ('    COMMAND_TYPE_' + type.upper () + ' = 0,\n')
        first = 0
    else:
        hfile.write ('    COMMAND_TYPE_' + type.upper () + ',\n')
hfile.write ('    COMMAND_TYPE_MAX,\n')
hfile.write ('} eLIBARCOMMANDS_COMMAND_TYPE;\n')
hfile.write ('\n')
hfile.write ('\n')
for type in alltypes:
    hfile.write ('typedef enum {\n')
    tname = alltypesNames[alltypes.index(type)].upper()
    first = 1
    for cmd in type:
        if 1 == first:
            hfile.write ('    ' + tname + '_CMD_' + cmd.upper () + ' = 0,\n')
            first = 0
        else:
            hfile.write ('    ' + tname + '_CMD_' + cmd.upper () + ',\n')
    hfile.write ('    ' + tname  + '_CMD_MAX,\n')
    hfile.write ('} eLIBARCOMMANDS_' + tname + '_CMD;\n')
    hfile.write ('\n')

hfile.write ('\n')
hfile.write ('extern libARCommandsCmd_t ***libARCommandsCmdList;\n')
hfile.write ('extern int *libARCommandsCmdTypesMaxId;\n')
hfile.write ('extern int libARCommandsListInitOk;\n')
hfile.write ('\n')
hfile.write ('int libARCommandsListInit ();\n')
hfile.write ('void libARCommandsListDestroy ();\n')
hfile.write ('libARCommandsCmd_t *getCommandArgsWithTypeAndId (eLIBARCOMMANDS_ARG_TYPE type, int id);\n')
hfile.write ('\n')
hfile.write ('#endif /* _LIBARCOMMANDS_COMMANDS_LIST_H_ */\n')

hfile.close ()
